import Head from "next/head";
import { useState } from "react";
import axios from "axios";
import Heading from "../../components/common/Heading";
import Navbar from "../../components/common/Navbar";
import KeyValueCard from "../../components/common/KeyValueCard";
import TimePeriodDropdown from "../../components/common/TimePeriodDropdown";
import InformationTable from "../../components/tables/InformationTable";
import DonutChart from "../../components/charts/DonutChart";
import VerticalBarChart from "../../components/charts/VerticalBarChart";
import LineChart from "../../components/charts/LineChart";
import styles from "../../styles/pages/user/User.module.css";
import {
  formatContestsDataForTable,
  formatProblemsDataForTable,
} from "../../helpers/organization";

const User = ({ userInformation, userContests, userProblems }) => {
  // The time period for which the user wants to view the statistics
  const [timePeriod, setTimePeriod] = useState("all_time");

  return (
    <div className={styles.container}>
      <Head>
        <title>Stats Portal - {userInformation.handle}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <div className={styles.stats_container}>
        {/* Heading */}
        <Heading
          prefixHeading={"statistics for"}
          mainHeading={userInformation.handle}
        />

        {/* User Information Cards */}
        <div className={styles.user_information_container}>
          <KeyValueCard
            cardKey={"User Since"}
            // We obtain the string in this format: "Weekday, Day Month Year"
            cardValue={userInformation["creation_date"]
              .split(" ")
              .splice(0, 4)
              .join(" ")}
            color={"#dc143c"}
          />
          <KeyValueCard
            cardKey={"Rank"}
            cardValue={userInformation["rank"]}
            color={"#2196f3"}
          />
          <KeyValueCard
            cardKey={"Rating"}
            cardValue={userInformation["rating"]}
            color={"#32cd32"}
          />
          <KeyValueCard
            cardKey={"Maximum Rating"}
            cardValue={userInformation["max_rating"]}
            color={"#f39c12"}
          />
        </div>

        <div className={styles.flex_wrap_container}>
          {/* Time Period Select Dropdown */}
          <TimePeriodDropdown
            timePeriod={timePeriod}
            setTimePeriod={setTimePeriod}
          />

          {/* Contests Statistics Table */}
          <div className={styles.half_chart_container}>
            <InformationTable
              title={"Contest Statistics"}
              data={formatContestsDataForTable(userContests[timePeriod])}
            />
          </div>
          {/* Problems Statistics Table */}
          <div className={styles.half_chart_container}>
            <InformationTable
              title={"Problem Statistics"}
              data={formatProblemsDataForTable(userProblems[timePeriod])}
            />
          </div>
          {/* Language Distribution Chart */}
          <div className={styles.half_chart_container}>
            <DonutChart
              title={`Languages Used by ${userInformation.handle}`}
              data={userProblems[timePeriod].languages}
            />
          </div>
          {/* Tag Distribution Donut Chart */}
          <div className={styles.half_chart_container}>
            <DonutChart
              title={`Problem Tags Solved by ${userInformation.handle}`}
              data={userProblems[timePeriod].tags}
            />
          </div>
          {/* Index Distribution Bar Chart */}
          <div className={styles.half_chart_container}>
            <VerticalBarChart
              title={`Problem Indexes Solved by ${userInformation.handle}`}
              data={userProblems[timePeriod].indexes}
              color={"#ff1744"}
              dataName={"Problems Solved"}
            />
          </div>
          {/* Ratings Distribution Bar Chart */}
          <div className={styles.half_chart_container}>
            <VerticalBarChart
              title={`Problem Ratings Solved by ${userInformation.handle}`}
              data={userProblems[timePeriod].ratings}
              color={"#2196f3"}
              dataName={"Problems Solved"}
            />
          </div>
          {/* Rating History Line Chart */}
          <div className={styles.full_chart_container}>
            <LineChart
              title={`Rating History for ${userInformation.handle}`}
              data={userContests[timePeriod].rating_history}
            />
          </div>
        </div>
      </div>
    </div>
  );
};

export default User;

export const getStaticProps = async (context) => {
  // Extracting handle from URL
  const handle = context.params.handle;

  // The base URL is common to information ("/"), user's contests ("/contests-participated")
  // and user's problems solved ("/problems-solved")
  const baseURL = `http://localhost:5000/users/${handle}`;

  // Getting the required statistics from the backend
  const userInformation = await axios.get(baseURL);
  const userContests = await axios.get(`${baseURL}/contests-participated`);
  const userProblems = await axios.get(`${baseURL}/problems-solved`);

  // Passing in the statistics as props to the page component
  return {
    props: {
      userInformation: await userInformation.data,
      userContests: await userContests.data,
      userProblems: await userProblems.data,
    },
    // If any request is made an hour after the last one, the page will be regenerated.
    // Only the requested page is regenerated, not the whole application.
    revalidate: 3600,
  };
};

export const getStaticPaths = async () => {
  // Getting information of all users from the database. We need this to
  // pregenerate the pages on build time.
  const URL = "http://localhost:5000/users";
  const users = await axios.get(URL);
  const usersData = await users.data;

  // Obtaining essentially an array of user handles to build the pages for each user.
  // This is run once at build time and so subsequent requests will serve static
  // pages, resulting in much lower load times.
  const paths = usersData.map((user) => ({
    params: { handle: user["handle"] },
  }));

  // If the path still doesn't exist after the static build, the page will be
  // server-rendered on-demand, if fallback is set to "blocking", instead of
  // displaying a 404. This is just a fallback in case of any mismatches between
  // backend database updates and the frontend static build.
  return {
    paths: paths,
    fallback: "blocking",
  };
};
