import Head from "next/head";
import axios from "axios";
import Heading from "../../components/common/Heading";
import Navbar from "../../components/common/Navbar";
import DescriptorCard from "../../components/common/DescriptorCard";
import styles from "../../styles/pages/leaderboards/Leaderboard.module.css";

const Leaderboards = ({ organizationName }) => {
  const leaderboards = [
    {
      title: "MOST PROBLEMS SOLVED",
      description: `Leaderboard for the most problems solved by the users of ${organizationName}.`,
      imageLink: "/images/problems_solved_img.png",
      buttonText: "View Leaderboard >>",
      buttonLink: "/leaderboards/problems-solved",
    },
    {
      title: "HIGHEST RATING INCREASE",
      description: `Leaderboard for the highest rating increase obtained by users of ${organizationName}.`,
      imageLink: "/images/rating_increase_img.png",
      buttonText: "View Leaderboard >>",
      buttonLink: "/leaderboards/highest-rating-increase",
    },
    {
      title: "MOST CONTESTS PARTICIPATED",
      description: `Leaderboard for the most contests participated by users of ${organizationName}.`,
      imageLink: "/images/contests_participated_img.png",
      buttonText: "View Leaderboard >>",
      buttonLink: "/leaderboards/contests-participated",
    },
    {
      title: "BEST CONTEST RANKS",
      description: `Leaderboard for the highest contest ranks achieved by users of ${organizationName}.`,
      imageLink: "/images/contest_rank_img.png",
      buttonText: "View Leaderboard >>",
      buttonLink: "/leaderboards/best-contest-ranks",
    },
  ];

  return (
    <div className={styles.container}>
      <Head>
        <title>Stats Portal - Leaderboards</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <div className={styles.stats_container}>
        {/* Heading */}
        <Heading
          prefixHeading={`view ${organizationName}'s`}
          mainHeading={"leaderboards"}
        />

        {/* Creating a descriptor card for each of the leaderboards in the leaderboards array */}
        <div className={styles.flex_wrap_container}>
          {leaderboards.map((leaderboard, index) => (
            <div className={styles.half_chart_container}>
              <DescriptorCard
                key={index}
                title={leaderboard.title}
                description={leaderboard.description}
                imageLink={leaderboard.imageLink}
                buttonText={leaderboard.buttonText}
                buttonLink={leaderboard.buttonLink}
              />
            </div>
          ))}
        </div>
      </div>
    </div>
  );
};

export default Leaderboards;

export const getStaticProps = async () => {
  // Obtain the data about the organization from the backend
  const organizationInformation = await axios.get(
    "http://localhost:5000/organization"
  );

  // Passing the organization name as a prop to the page component. The name is the only information we require on this page.
  return {
    props: {
      organizationName: await organizationInformation.data.name,
    },
  };
};
