import Head from "next/head";
import { useState } from "react";
import axios from "axios";
import Navbar from "../../components/common/Navbar";
import Heading from "../../components/common/Heading";
import TimePeriodDropdown from "../../components/common/TimePeriodDropdown";
import LeaderboardTable from "../../components/tables/LeaderboardTable";
import styles from "../../styles/pages/leaderboards/Leaderboard.module.css";
import { obtainDataCountPerUser } from "../../helpers/leaderboards";

const ProblemsSolved = ({ problemsData }) => {
  const [timePeriod, setTimePeriod] = useState("all_time");

  return (
    <div className={styles.container}>
      <Head>
        <title>Stats Portal - Problems Solved</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <div className={styles.stats_container}>
        {/* Heading */}
        <Heading
          prefixHeading={"leaderboard for"}
          mainHeading={"problems solved"}
        />

        {/* Time Period Select Dropdown */}
        <TimePeriodDropdown
          timePeriod={timePeriod}
          setTimePeriod={setTimePeriod}
        />

        {/* Leaderboard Table */}
        <div className={styles.table_container}>
          <LeaderboardTable
            title={"Most Problems Solved"}
            data={problemsData[timePeriod]}
            attribute={"total_problems"} // This has to be the same as that supplied to obtainDataCountPerUser in getStaticProps
            statisticName={"Problems Solved"} // The column name for the statistic corresponding to the attribute
            sortingOrder={"desc"} // Either "asc" or "desc"
          />
        </div>
      </div>
    </div>
  );
};

export default ProblemsSolved;

export const getStaticProps = async () => {
  // Obtain the data about information of users in the organization and
  // problems solved by the organization
  const usersInformation = await axios.get("http://localhost:5000/users");
  const problemsSolved = await axios.get(
    "http://localhost:5000/users/problems-solved"
  );

  // Retrieve the data from the response
  const usersData = await usersInformation.data;
  const problemsSolvedData = await problemsSolved.data;

  // Obtain the data count per user
  const dataCountPerUser = await obtainDataCountPerUser(
    usersData,
    problemsSolvedData,
    "total_problems"
  );

  // Pass the data to the component as props
  return {
    props: {
      problemsData: dataCountPerUser,
    },
    // If any request is made an hour after the last one, the page will be regenerated.
    // Only the requested page is regenerated, not the whole application.
    revalidate: 3600,
  };
};
